### ISSUE TITLE
Player loosing items

### ISSUE THREAD

**Issue by brandonHD** [multidude/Jail#8]
I am using the Jail plugin version 2.6.5 on my Spigot 1.8.8 server (The newest ones had a lot of commands missing) and when I jailed a player to test it, they lost all of their items. I did define a chest for all the cells. Any help would be great.

**Comment by graywolf336** [comment]
The old versions have that as a known issue and will always due to the massive amount of work required to get items to no longer be lost. If the newer versions don't have commands, please open an issue about it.

**Comment by brandonHD** [comment]
I mean... Why? I clearly said that in this issue. So I should open another ticket to try and address the same problem?

**Comment by graywolf336** [comment]
The new version isn't located in this repository. Also, you will need to
provide detailed examples of which commands are missing.
